### ISSUE TITLE
test

### ISSUE THREAD

**Issue by hyang024** [vptcoder/GroupBuy-CSIT321#52]
test

**Comment by vptcoder** [comment]
Hi @hyang024 from now on testing process please follow this:
1. You test based on the test plan
2. If something failed, create an issue here
3. assign the issue to me
4. label as bug
5. assign to 'GroupBuy project'
6. assign to the corresponding 'Milestone'
7. Wait for me to fix the issue
8. I will then assign back for you to re-test
9. if re-test pass -> put comment that it passed and click 'Close with comment'
10. if re-test fail -> 'Comment' what's failing and assign back to me again, we repeat step 7-10 until issue is fixed.

**Comment by hyang024** [comment]
okay, noted
